site_name: LabÁudio - 2016 - 2S
pages:
- Home: 'index.md'
- Aulas:
    - 'Introdução à produção sonora e som digital' : 'aulas/producao-sonora.md'
    - 'História do som em videogames' : 'aulas/historia-som.md'
    - 'Percepção sonora e musical' : 'aulas/percepcao-sonora.md'
- Mais infos :
    - Glossário : 'glossario.md'
    - Ferramentas : 'ferramentas.md'
    - Referências : 'referencias.md'
theme: bootstrap
extra_css:
  - css/extra.css
extra_javascript:
  - js/extra.js
markdown_extensions:
  - smarty
  - sane_lists
site_favicon: 'imgs/singing.gif'
repo_url: https://github.com/puccjogos/labaudio-2016-2s